version: '3'
services:
  app:
    build: .
    volumes:
      - ./app:/app/app
    command: ["python3", "main.py"]
    env_file:
      - .env
    ports:
      - "8995:8995"
    container_name: simple_discord_bot